Valid_Plugins = {'Ahmia I2P Darkweb Search': {'Requires_Configuration': False, 'Requires_Limit': True, 'Module': 'plugins.Ahmia_Darkweb_Search'},
'Ahmia Tor Darkweb Search': {'Requires_Configuration': False, 'Requires_Limit': True, 'Module': 'plugins.Ahmia_Darkweb_Search'},
'Apple Store Search': {'Requires_Configuration': True, 'Requires_Limit': True, 'Module': 'plugins.Apple_Store_Search'},
'BSB Search': {'Requires_Configuration': False, 'Requires_Limit': False, 'Module': 'plugins.BSB_Search'},
'Blockchain - Bitcoin Address Search': {'Requires_Configuration': False, 'Requires_Limit': True, 'Module': 'plugins.Blockchain_Search'},
'Blockchain - Bitcoin Cash Address Search': {'Requires_Configuration': False, 'Requires_Limit': True, 'Module': 'plugins.Blockchain_Search'},
'Blockchain - Bitcoin Cash Transaction Search': {'Requires_Configuration': False, 'Requires_Limit': True, 'Module': 'plugins.Blockchain_Search'},
'Blockchain - Bitcoin Transaction Search': {'Requires_Configuration': False, 'Requires_Limit': True, 'Module': 'plugins.Blockchain_Search'},
'Blockchain - Ethereum Address Search': {'Requires_Configuration': False, 'Requires_Limit': True, 'Module': 'plugins.Blockchain_Search'},
'Blockchain - Ethereum Transaction Search': {'Requires_Configuration': False, 'Requires_Limit': True, 'Module': 'plugins.Blockchain_Search'},
'Blockchain - Monero Transaction Search': {'Requires_Configuration': False, 'Requires_Limit': False, 'Module': 'plugins.Blockchain_Search'},
'Builtwith Search': {'Requires_Configuration': False, 'Requires_Limit': False, 'Module': 'plugins.BuiltWith_Search', 'Organisation_Presets': "website"},
'Business Search - American Central Index Key': {'Requires_Configuration': False, 'Requires_Limit': False, 'Module': 'plugins.American_Business_Search'},
'Business Search - American Company Name': {'Requires_Configuration': False, 'Requires_Limit': True, 'Module': 'plugins.American_Business_Search', 'Organisation_Presets': "name"},
'Business Search - Australian Business Number': {'Requires_Configuration': False, 'Requires_Limit': False, 'Module': 'plugins.Australian_Business_Search'},
'Business Search - Australian Company Name': {'Requires_Configuration': False, 'Requires_Limit': True, 'Module': 'plugins.Australian_Business_Search', 'Organisation_Presets': "name"},
'Business Search - Canadian Business Number': {'Requires_Configuration': False, 'Requires_Limit': False, 'Module': 'plugins.Canadian_Business_Search'},
'Business Search - Canadian Company Name': {'Requires_Configuration': False, 'Requires_Limit': True, 'Module': 'plugins.Canadian_Business_Search', 'Organisation_Presets': "name"},
'Business Search - New Zealand Business Number': {'Requires_Configuration': False, 'Requires_Limit': False, 'Module': 'plugins.NZ_Business_Search'},
'Business Search - New Zealand Company Name': {'Requires_Configuration': False, 'Requires_Limit': True, 'Module': 'plugins.NZ_Business_Search', 'Organisation_Presets': "name"},
'Business Search - United Kingdom Business Number': {'Requires_Configuration': True, 'Requires_Limit': False, 'Module': 'plugins.UK_Business_Search'},
'Business Search - United Kingdom Company Name': {'Requires_Configuration': True, 'Requires_Limit': True, 'Module': 'plugins.UK_Business_Search', 'Organisation_Presets': "name"},
'Certificate Transparency - CRT.sh': {'Requires_Configuration': False, 'Requires_Limit': False, 'Module': 'plugins.Certificate_Transparency_CRT', 'Organisation_Presets': "domain"},
'Certificate Transparency - SSLMate': {'Requires_Configuration': True, 'Requires_Limit': False, 'Module': 'plugins.Certificate_Transparency_SSLMate', 'Organisation_Presets': "domain"},
'Craigslist Search': {'Requires_Configuration': True, 'Requires_Limit': True, 'Module': 'plugins.Craigslist_Search'},
'DNS Reconnaissance Search': {'Requires_Configuration': False, 'Requires_Limit': False, 'Module': 'plugins.DNS_Recon_Search', 'Organisation_Presets': "domain"},
'Default Password Search': {'Requires_Configuration': False, 'Requires_Limit': True, 'Module': 'plugins.Default_Password_Search'},
'Doing Business Search': {'Requires_Configuration': False, 'Requires_Limit': False, 'Module': 'plugins.Doing_Business_Search'},
'Domain Fuzzer - All Extensions': {'Requires_Configuration': False, 'Requires_Limit': False, 'Module': 'plugins.Domain_Fuzzer', 'Organisation_Presets': "domain"},
'Domain Fuzzer - Expired Global Domain Suffixes': {'Requires_Configuration': False, 'Requires_Limit': True, 'Module': 'plugins.Domain_Fuzzer', 'Organisation_Presets': "domain"},
'Domain Fuzzer - Global Domain Suffixes': {'Requires_Configuration': False, 'Requires_Limit': False, 'Module': 'plugins.Domain_Fuzzer', 'Organisation_Presets': "domain"},
'Domain Fuzzer - Punycode (Asian)': {'Requires_Configuration': False, 'Requires_Limit': False, 'Module': 'plugins.Domain_Fuzzer', 'Organisation_Presets': "domain"},
'Domain Fuzzer - Punycode (Latin Comprehensive)': {'Requires_Configuration': False, 'Requires_Limit': False, 'Module': 'plugins.Domain_Fuzzer', 'Organisation_Presets': "domain"},
'Domain Fuzzer - Punycode (Latin Condensed)': {'Requires_Configuration': False, 'Requires_Limit': False, 'Module': 'plugins.Domain_Fuzzer', 'Organisation_Presets': "domain"},
'Domain Fuzzer - Punycode (Middle Eastern)': {'Requires_Configuration': False, 'Requires_Limit': False, 'Module': 'plugins.Domain_Fuzzer', 'Organisation_Presets': "domain"},
'Domain Fuzzer - Punycode (Native American)': {'Requires_Configuration': False, 'Requires_Limit': False, 'Module': 'plugins.Domain_Fuzzer', 'Organisation_Presets': "domain"},
'Domain Fuzzer - Punycode (North African)': {'Requires_Configuration': False, 'Requires_Limit': False, 'Module': 'plugins.Domain_Fuzzer', 'Organisation_Presets': "domain"},
'Domain Fuzzer - Regular Domain Suffixes': {'Requires_Configuration': False, 'Requires_Limit': False, 'Module': 'plugins.Domain_Fuzzer', 'Organisation_Presets': "domain"},
'DuckDuckGo Search': {'Requires_Configuration': False, 'Requires_Limit': True, 'Module': 'plugins.DuckDuckGo_Search'},
'Ebay Search': {'Requires_Configuration': True, 'Requires_Limit': True, 'Module': 'plugins.Ebay_Search'},
'Email Reputation Search': {'Requires_Configuration': True, 'Requires_Limit': False, 'Module': 'plugins.Email_Reputation_Search', 'Organisation_Presets': "identity_emails"},
'Email Verification Search': {'Requires_Configuration': False, 'Requires_Limit': False, 'Module': 'plugins.Email_Verification_Search', 'Organisation_Presets': "identity_emails"},
'Flickr Search': {'Requires_Configuration': True, 'Requires_Limit': True, 'Module': 'plugins.Flickr_Search'},
'GitHub Repository Search': {'Requires_Configuration': True, 'Requires_Limit': True, 'Module': 'plugins.GitHub_Search'},
'Google Play Store Search': {'Requires_Configuration': False, 'Requires_Limit': True, 'Module': 'plugins.Google_Play_Store_Search'},
'Google Search': {'Requires_Configuration': True, 'Requires_Limit': True, 'Module': 'plugins.Google_Search'},
'Greynoise IP Search': {'Requires_Configuration': False, 'Requires_Limit': False, 'Module': 'plugins.Greynoise_IP_Search'},
'Have I Been Pwned - Account Search': {'Requires_Configuration': True, 'Requires_Limit': True, 'Module': 'plugins.Have_I_Been_Pwned'},
'Have I Been Pwned - Breach Search': {'Requires_Configuration': True, 'Requires_Limit': False, 'Module': 'plugins.Have_I_Been_Pwned'},
'Have I Been Pwned - Email Search': {'Requires_Configuration': True, 'Requires_Limit': False, 'Module': 'plugins.Have_I_Been_Pwned', 'Organisation_Presets': "identity_emails"},
'Have I Been Pwned - Password Search': {'Requires_Configuration': True, 'Requires_Limit': False, 'Module': 'plugins.Have_I_Been_Pwned'},
'Hunter Search - Domain': {'Requires_Configuration': True, 'Requires_Limit': True, 'Module': 'plugins.Hunter_Search', 'Organisation_Presets': "domain"},
'Hunter Search - Email': {'Requires_Configuration': True, 'Requires_Limit': True, 'Module': 'plugins.Hunter_Search', 'Organisation_Presets': "identity_emails"},
'IP Stack Search': {'Requires_Configuration': True, 'Requires_Limit': False, 'Module': 'plugins.IPStack_Search'},
'Instagram - Post Search': {'Requires_Configuration': False, 'Requires_Limit': False, 'Module': 'plugins.Instagram_Search'},
'Instagram - Tag Search': {'Requires_Configuration': False, 'Requires_Limit': True, 'Module': 'plugins.Instagram_Search'},
'Instagram - User Search': {'Requires_Configuration': False, 'Requires_Limit': True, 'Module': 'plugins.Instagram_Search'},
'IntelligenceX Search': {'Requires_Configuration': True, 'Requires_Limit': True, 'Module': 'plugins.IntelligenceX_Search', 'Organisation_Presets': "domain"},
'Kik Search': {'Requires_Configuration': False, 'Requires_Limit': False, 'Module': 'plugins.Kik_Search'},
'Library Genesis Search': {'Requires_Configuration': False, 'Requires_Limit': True, 'Module': 'plugins.Library_Genesis_Search'},
'Naver Search': {'Requires_Configuration': True, 'Requires_Limit': True, 'Module': 'plugins.Naver_Search'},
'OK Search - Group': {'Requires_Configuration': True, 'Requires_Limit': False, 'Module': 'plugins.OK_Search'},
'OK Search - User': {'Requires_Configuration': True, 'Requires_Limit': False, 'Module': 'plugins.OK_Search'},
'Phishstats Search': {'Requires_Configuration': False, 'Requires_Limit': True, 'Module': 'plugins.Phishstats_Search', 'Organisation_Presets': "domain"},
'Phone Search - Cellular Number': {'Requires_Configuration': False, 'Requires_Limit': False, 'Module': 'plugins.Phone_Search', 'Organisation_Presets': "identity_phones"},
'Phone Search - IMEI Number': {'Requires_Configuration': False, 'Requires_Limit': False, 'Module': 'plugins.Phone_Search'},
'Phone Search - IMSI Number': {'Requires_Configuration': False, 'Requires_Limit': False, 'Module': 'plugins.Phone_Search'},
'Phone Search - ISPC Number': {'Requires_Configuration': False, 'Requires_Limit': False, 'Module': 'plugins.Phone_Search'},
'Phone Search - SIM Number': {'Requires_Configuration': False, 'Requires_Limit': False, 'Module': 'plugins.Phone_Search'},
'Pinterest - Board Search': {'Requires_Configuration': True, 'Requires_Limit': True, 'Module': 'plugins.Pinterest_Search'},
'Pinterest - Pin Search': {'Requires_Configuration': True, 'Requires_Limit': False, 'Module': 'plugins.Pinterest_Search'},
'RSS Feed Search': {'Requires_Configuration': False, 'Requires_Limit': True, 'Module': 'plugins.RSS_Feed_Search', 'Organisation_Presets': "name"},
'Reddit Search': {'Requires_Configuration': True, 'Requires_Limit': True, 'Module': 'plugins.Reddit_Search'},
'Shodan Search - IP Address': {'Requires_Configuration': True, 'Requires_Limit': False, 'Module': 'plugins.Shodan_Search'},
'Shodan Search - Query': {'Requires_Configuration': True, 'Requires_Limit': True, 'Module': 'plugins.Shodan_Search'},
'Threat Crowd - Antivirus Search': {'Requires_Configuration': False, 'Requires_Limit': False, 'Module': 'plugins.Threat_Crowd_Search'},
'Threat Crowd - Domain Search': {'Requires_Configuration': False, 'Requires_Limit': False, 'Module': 'plugins.Threat_Crowd_Search', 'Organisation_Presets': "domain"},
'Threat Crowd - Email Search': {'Requires_Configuration': False, 'Requires_Limit': False, 'Module': 'plugins.Threat_Crowd_Search', 'Organisation_Presets': "identity_emails"},
'Threat Crowd - IP Address Search': {'Requires_Configuration': False, 'Requires_Limit': False, 'Module': 'plugins.Threat_Crowd_Search'},
'Threat Crowd - Virus Report Search': {'Requires_Configuration': False, 'Requires_Limit': False, 'Module': 'plugins.Threat_Crowd_Search'},
'Torrent Search': {'Requires_Configuration': False, 'Requires_Limit': True, 'Module': 'plugins.Torrent_Search'},
'Tumblr Search': {'Requires_Configuration': True, 'Requires_Limit': False, 'Module': 'plugins.Tumblr_Search'},
'Twitter Search': {'Requires_Configuration': True, 'Requires_Limit': True, 'Module': 'plugins.Twitter_Search'},
'Username Search': {'Requires_Configuration': False, 'Requires_Limit': True, 'Module': 'plugins.Username_Search', 'Organisation_Presets': "identity_usernames"},
'Vehicle Registration Search': {'Requires_Configuration': False, 'Requires_Limit': False, 'Module': 'plugins.Vehicle_Registration_Search'},
'Virus Total Search - Domain': {'Requires_Configuration': True, 'Requires_Limit': False, 'Module': 'plugins.Virus_Total_Search', 'Organisation_Presets': "domain"},
'Virus Total Search - File Hash': {'Requires_Configuration': True, 'Requires_Limit': False, 'Module': 'plugins.Virus_Total_Search'},
'Virus Total Search - IP Address': {'Requires_Configuration': True, 'Requires_Limit': False, 'Module': 'plugins.Virus_Total_Search'},
'Virus Total Search - URL': {'Requires_Configuration': True, 'Requires_Limit': False, 'Module': 'plugins.Virus_Total_Search', 'Organisation_Presets': "website"},
'Vkontakte - Group Search': {'Requires_Configuration': False, 'Requires_Limit': True, 'Module': 'plugins.Vkontakte_Search'},
'Vkontakte - User Search': {'Requires_Configuration': False, 'Requires_Limit': True, 'Module': 'plugins.Vkontakte_Search'},
'Vulners Search': {'Requires_Configuration': True, 'Requires_Limit': True, 'Module': 'plugins.Vulners_Search'},
'Windows Store Search': {'Requires_Configuration': True, 'Requires_Limit': True, 'Module': 'plugins.Windows_Store_Search'},
'Yandex Search': {'Requires_Configuration': True, 'Requires_Limit': True, 'Module': 'plugins.Yandex_Search'},
'YouTube Search': {'Requires_Configuration': True, 'Requires_Limit': True, 'Module': 'plugins.YouTube_Search'}}